SELECT COUNT(*) FROM raw.customers;
SELECT COUNT(*) FROM raw.orders;
SELECT COUNT(*) FROM raw.order_items;
SELECT COUNT(*) FROM raw.products;
SELECT COUNT(*) FROM raw.payments;
SELECT COUNT(*) FROM raw.reviews;
SELECT COUNT(*) FROM raw.sellers;
SELECT COUNT(*) FROM raw.geolocation;
SELECT COUNT(*) FROM raw.product_category_translation;