/* =============================================================================
   1. MONTHLY REVENUE
   Aggregates total monetary revenue per month based on order placement timestamps.
   ============================================================================= */

CREATE OR ALTER VIEW analytics.monthly_revenue AS
SELECT
    -- Truncate timestamp to the first day of each month for monthly grouping
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    -- Sum of all payments recorded for orders in that month
    SUM(p.payment_value) AS revenue
FROM raw.orders AS o
-- Join with payments to get the monetary value of each order
JOIN raw.payments AS p
    ON o.order_id = p.order_id
GROUP BY month
ORDER BY month;

-- Preview monthly revenue trend over time
SELECT *
FROM analytics.monthly_revenue;


/* =============================================================================
   2. MONTHLY ORDER VOLUME
   Tracks overall order counts per month to monitor transaction growth.
   ============================================================================= */

CREATE OR REPLACE VIEW analytics.monthly_orders AS
SELECT
    -- Truncate purchase timestamp to month
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    -- Count total unique orders placed in each month
    COUNT(o.order_id) AS order_count
FROM raw.orders AS o
GROUP BY month
ORDER BY month;

-- Preview monthly order volume trend
SELECT *
FROM analytics.monthly_orders;


/* =============================================================================
   3. SALES PERFORMANCE BY CUSTOMER STATE
   Analyzes geographic distribution of order volume and total revenue.
   ============================================================================= */

CREATE OR REPLACE VIEW analytics.state_sales AS
SELECT
    c.customer_state,
    -- Count distinct order IDs to avoid duplicate counts if an order has multiple payments
    COUNT(DISTINCT o.order_id) AS total_orders,
    -- Total payment value generated from customers in this state
    SUM(p.payment_value) AS total_revenue
FROM raw.customers AS c
JOIN raw.orders AS o
    ON c.customer_id = o.customer_id
JOIN raw.payments AS p
    ON o.order_id = p.order_id
GROUP BY c.customer_state;

-- Retrieve states ranked by total revenue (highest to lowest)
SELECT *
FROM analytics.state_sales
ORDER BY total_revenue DESC;


/* =============================================================================
   4. SALES PERFORMANCE BY PRODUCT CATEGORY
   Evaluates top-performing categories by units sold and gross merchandise value.
   ============================================================================= */

CREATE OR REPLACE VIEW analytics.category_sales AS
SELECT
    pr.product_category_name,
    -- Count order item lines (representing units sold)
    COUNT(oi.order_item_id) AS total_units,
    -- Sum item prices to get total item-level revenue (excluding shipping/fees)
    SUM(oi.price) AS total_revenue
FROM raw.products AS pr
JOIN raw.order_items AS oi
    ON pr.product_id = oi.product_id
GROUP BY pr.product_category_name
ORDER BY total_revenue DESC;

-- View categories ordered by revenue performance
SELECT *
FROM analytics.category_sales
ORDER BY total_revenue DESC;


/* =============================================================================
   5. SALES PERFORMANCE BY INDIVIDUAL PRODUCT
   Identifies best-selling individual SKUs/products.
   ============================================================================= */

CREATE OR REPLACE VIEW analytics.product_sales AS
SELECT
    pr.product_id,
    -- Total units sold for each individual product
    COUNT(oi.order_item_id) AS total_units,
    -- Total revenue generated by each product
    SUM(oi.price) AS total_revenue
FROM raw.products AS pr
JOIN raw.order_items AS oi
    ON pr.product_id = oi.product_id
GROUP BY pr.product_id
ORDER BY total_revenue DESC;

-- View top-performing individual products
SELECT *
FROM analytics.product_sales
ORDER BY total_revenue DESC;


/* =============================================================================
   6. CUSTOMER SEGMENTATION (REPEAT VS. ONE-TIME)
   Classifies customers by purchase frequency and compares their revenue share.
   ============================================================================= */

CREATE OR REPLACE VIEW analytics.customer_analysis AS
WITH customer_orders AS (
    -- Calculate total lifetime orders per unique person (customer_unique_id)
    SELECT
        c.customer_unique_id,
        COUNT(o.order_id) AS order_count
    FROM raw.customers AS c
    JOIN raw.orders AS o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
),

customer_revenue AS (
    -- Calculate total lifetime revenue per unique person
    SELECT
        c.customer_unique_id,
        SUM(p.payment_value) AS total_revenue
    FROM raw.customers AS c
    JOIN raw.orders AS o
        ON c.customer_id = o.customer_id
    JOIN raw.payments AS p
        ON o.order_id = p.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    -- Segment customers based on order frequency
    CASE
        WHEN co.order_count > 1 THEN 'Repeated Customer'
        ELSE 'One Time Customer'
    END AS customer_type,
    -- Total count of unique customers in each segment
    COUNT(*) AS customer_count,
    -- Total revenue generated by each segment
    SUM(cr.total_revenue) AS total_revenue
FROM customer_orders AS co
JOIN customer_revenue AS cr
    ON co.customer_unique_id = cr.customer_unique_id
GROUP BY customer_type
ORDER BY total_revenue DESC;

-- View customer retention and revenue contribution summary
SELECT *
FROM analytics.customer_analysis;


/* =============================================================================
   7. DELIVERY DURATION ANALYSIS
   Measures fulfillment lead time from purchase to customer delivery.
   ============================================================================= */

CREATE OR REPLACE VIEW analytics.delivery_analysis AS
SELECT
    order_id,
    order_purchase_timestamp,
    order_delivered_customer_date,
    -- Calculate duration in seconds (epoch difference) and divide by 86,400 to convert to days
    EXTRACT(
        EPOCH FROM (
            order_delivered_customer_date
            - order_purchase_timestamp
        )
    ) / 86400 AS delivery_days
FROM raw.orders
-- Exclude unfulfilled, in-transit, or canceled orders lacking a delivery timestamp
WHERE order_delivered_customer_date IS NOT NULL;

-- Sample the first 20 delivery records
SELECT *
FROM analytics.delivery_analysis
LIMIT 20;

-- Aggregate delivery metrics (volume, average, fastest, and slowest delivery times)
SELECT
    COUNT(*) AS delivered_orders,
    ROUND(AVG(delivery_days), 2) AS avg_delivery_days,
    ROUND(MIN(delivery_days), 2) AS min_delivery_days,
    ROUND(MAX(delivery_days), 2) AS max_delivery_days
FROM analytics.delivery_analysis;